version: 2.32.3

name: react-test-app

services:
  web:
    build: .
    container_name: web-app
    environment:
      - VITE_HOST=${VITE_HOST}
      - VITE_PORT=${VITE_PORT}
    ports:
      - 3001:${VITE_PORT}
